// <auto-generated />
namespace Echange_Livres.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateBook));
        
        string IMigrationMetadata.Id
        {
            get { return "202212131533096_updateBook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
